server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      max-lifetime: 58000

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
